# Generated by Django 3.2.2 on 2021-06-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famdanuch', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('namedanuch', models.CharField(max_length=100, verbose_name='Имя')),
                ('otchdanuch', models.CharField(blank=True, max_length=100, verbose_name='Отчетсво')),
                ('daterogddanuch', models.DateField()),
                ('nomdoma', models.CharField(max_length=100, verbose_name='Номер дома')),
                ('nomkvart', models.CharField(max_length=100, verbose_name='Номер квартиры')),
            ],
            options={
                'verbose_name': 'фио индивида',
                'verbose_name_plural': 'фио индивида',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viddoc', models.CharField(max_length=100, verbose_name='фио')),
                ('datedoc', models.CharField(max_length=100, verbose_name='фио')),
                ('nomerdoc', models.CharField(max_length=100, verbose_name='фио')),
                ('seriadoc', models.CharField(max_length=100, verbose_name='фио')),
                ('kemvidan', models.CharField(max_length=100, verbose_name='фио')),
                ('opisandoc', models.CharField(max_length=100, verbose_name='фио')),
                ('fiouch', models.CharField(max_length=100, verbose_name='фио')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=20, verbose_name='Номер группы')),
                ('categ', models.CharField(max_length=20, verbose_name='Категория')),
                ('fio', models.TextField(verbose_name='ФИО')),
                ('nach_obuch', models.DateField(verbose_name='Начало обучения')),
                ('konec_obuch', models.DateField(verbose_name='Конец обучения')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
            },
        ),
        migrations.CreateModel(
            name='Naspunct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimnaspunct', models.CharField(max_length=100, verbose_name='Наименование населенного пункта')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
        migrations.CreateModel(
            name='Otchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomgrup', models.CharField(max_length=20, verbose_name='Номер группы')),
                ('datenach', models.DateField(max_length=20, verbose_name='Дата начала обучения')),
                ('kolvo', models.CharField(max_length=20, verbose_name='Количество челвоек')),
                ('kolvozdav', models.CharField(max_length=20, verbose_name='Количесвто сдавших экзамен')),
                ('sotrud', models.CharField(max_length=20, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчет',
            },
        ),
        migrations.CreateModel(
            name='Progobuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(max_length=10, verbose_name='Категория')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('temi', models.TextField(verbose_name='Темы')),
                ('chasi', models.CharField(max_length=2, verbose_name='Часы')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программа обучения',
            },
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60, verbose_name='ФИО')),
                ('date_rogd', models.DateField(verbose_name='Дата рождения')),
                ('dolgn', models.CharField(max_length=60, verbose_name='Должность')),
                ('ucheniki', models.TextField(max_length=500, verbose_name='Ученики')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Tranport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Навзание')),
                ('categ', models.CharField(max_length=5, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Справочник транспорта',
                'verbose_name_plural': 'Справочник трансопрта',
            },
        ),
        migrations.CreateModel(
            name='Ucheniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60, verbose_name='ФИО')),
                ('gruppa', models.CharField(max_length=10, verbose_name='Группа')),
                ('date_rogd', models.DateField(verbose_name='Дата рождения')),
                ('nomdog', models.CharField(max_length=60, verbose_name='Номер договора')),
                ('nomspravki', models.CharField(max_length=60, verbose_name='Номер медицинской справки')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Ulici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naimulici', models.CharField(max_length=100, verbose_name='Наименование улицы')),
            ],
            options={
                'verbose_name': 'Улицы',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='Zurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiouch', models.CharField(max_length=100, verbose_name='фио')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
        migrations.CreateModel(
            name='Trvperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosnomer', models.CharField(max_length=60, verbose_name='Гос.Номер')),
                ('nazvavto', models.CharField(max_length=20, verbose_name='Макрка, модель')),
                ('tip_transm', models.CharField(max_length=20, verbose_name='Тип трансмиссии')),
                ('prog_obuch', models.CharField(max_length=60, verbose_name='Программа обучения')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki')),
            ],
            options={
                'verbose_name': 'Транспорт в период обучения',
                'verbose_name_plural': 'Транспорт в период обучения',
            },
        ),
        migrations.CreateModel(
            name='Rasp_teor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_zan', models.DateTimeField(verbose_name='Дата занятия')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki')),
                ('nazv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
            options={
                'verbose_name': 'Расписание теоретических занятий',
                'verbose_name_plural': 'Расписание теоретических занятий',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdog', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('datesost', models.DateField()),
                ('stoimostobuch', models.PositiveIntegerField(max_length=20, verbose_name='Стоимость обучения')),
                ('daterastor', models.DateField()),
                ('prichrast', models.CharField(blank=True, max_length=100, verbose_name='Причина расторжения')),
                ('datepolnop', models.DateField()),
                ('datenach', models.DateField(default=None)),
                ('dateokonch', models.DateField(default=None)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.progobuch')),
                ('uchenik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.danuch')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договор',
            },
        ),
        migrations.AddField(
            model_name='danuch',
            name='naspunkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.naspunct'),
        ),
        migrations.AddField(
            model_name='danuch',
            name='ulica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ulici'),
        ),
    ]
