# Generated by Django 3.2.2 on 2021-06-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazv', models.CharField(max_length=20, verbose_name='Номер группы')),
                ('categ', models.CharField(max_length=20, verbose_name='Категория')),
                ('nach_obuch', models.DateField(verbose_name='Начало обучения')),
                ('konec_obuch', models.DateField(verbose_name='Конец обучения')),
            ],
            options={
                'verbose_name': 'Список групп',
                'verbose_name_plural': 'Список групп',
            },
        ),
        migrations.CreateModel(
            name='Otchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomgrup', models.CharField(max_length=20, verbose_name='Номер группы')),
                ('datenach', models.DateField(max_length=20, verbose_name='Дата начала обучения')),
                ('kolvo', models.CharField(max_length=20, verbose_name='Количество челвоек')),
                ('kolvozdav', models.CharField(max_length=20, verbose_name='Количесвто сдавших экзамен')),
                ('sotrud', models.CharField(max_length=20, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчет',
            },
        ),
        migrations.CreateModel(
            name='Progobuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(max_length=10, verbose_name='Категория')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('temi', models.TextField(verbose_name='Темы')),
                ('chasi', models.CharField(max_length=2, verbose_name='Часы')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программа обучения',
            },
        ),
        migrations.CreateModel(
            name='Sotrudniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('fam', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('otch', models.CharField(max_length=250, null=True, verbose_name='Отчество')),
                ('fioSotr', models.CharField(max_length=250, verbose_name='ФИО')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Электронный адрес')),
                ('photo', models.CharField(max_length=150, verbose_name='Фотография')),
                ('date_rogd', models.DateField(verbose_name='Дата рождения')),
                ('dolgn', models.CharField(max_length=60, verbose_name='Должность')),
                ('ucheniki', models.TextField(max_length=500, verbose_name='Ученики')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Tranport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Навзание')),
                ('categ', models.CharField(max_length=5, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Справочник транспорта',
                'verbose_name_plural': 'Справочник трансопрта',
            },
        ),
        migrations.CreateModel(
            name='Ucheniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('fam', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('otch', models.CharField(max_length=250, null=True, verbose_name='Отчество')),
                ('fioUch', models.CharField(max_length=60, verbose_name='ФИО')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес проживания')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=150, verbose_name='Электронынй адрес')),
                ('photo', models.CharField(max_length=150, verbose_name='Фотография')),
                ('gruppa', models.CharField(max_length=10, verbose_name='Группа')),
                ('date_rogd', models.DateField(verbose_name='Дата рождения')),
                ('nomdog', models.CharField(max_length=60, verbose_name='Номер договора')),
                ('nomspravki', models.CharField(max_length=60, verbose_name='Номер медицинской справки')),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Zurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_zurnal', models.CharField(max_length=20, verbose_name='Номер Журнала')),
                ('date_otkr', models.DateField(verbose_name='Дата открытия')),
                ('nazv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.group')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
        migrations.CreateModel(
            name='Trvperiod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosnomer', models.CharField(max_length=60, verbose_name='Гос.Номер')),
                ('nazvavto', models.CharField(max_length=20, verbose_name='Макрка, модель')),
                ('tip_transm', models.CharField(max_length=20, verbose_name='Тип трансмиссии')),
                ('prog_obuch', models.CharField(max_length=60, verbose_name='Программа обучения')),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki')),
            ],
            options={
                'verbose_name': 'Транспорт в период обучения',
                'verbose_name_plural': 'Транспорт в период обучения',
            },
        ),
        migrations.CreateModel(
            name='Rasp_teor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_zan', models.DateTimeField(verbose_name='Дата занятия')),
                ('tema', models.CharField(max_length=250, verbose_name='Тема занятия')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('fioSotr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki', verbose_name='Фио сотрудника')),
            ],
            options={
                'verbose_name': 'Расписание теоретических занятий',
                'verbose_name_plural': 'Расписание теоретических занятий',
            },
        ),
        migrations.CreateModel(
            name='PosZurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otmetka_pos', models.CharField(max_length=20, verbose_name='Посещаемость')),
                ('date_zan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rasp_teor', verbose_name='Дата занятия')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика')),
                ('nomer_zurnal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zurnal')),
            ],
            options={
                'verbose_name': 'Позиция журнала',
                'verbose_name_plural': 'Позиции журнала',
            },
        ),
        migrations.CreateModel(
            name='DrivingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата занятия')),
                ('dlitelnost', models.FloatField(verbose_name='Продолжительность')),
                ('hoursleft', models.FloatField(verbose_name='Осталось часов')),
                ('comment', models.CharField(max_length=250, verbose_name='Комментарий инструктора')),
                ('fioSotr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sotrudniki', verbose_name='Фио сотрудника')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ucheniki', verbose_name='Фио ученика')),
            ],
            options={
                'verbose_name': 'Карточка вождения',
                'verbose_name_plural': 'Карточки вождения',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomerdog', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('datesost', models.DateField()),
                ('stoimostobuch', models.PositiveIntegerField(verbose_name='Стоимость обучения')),
                ('daterastor', models.DateField()),
                ('prichrast', models.CharField(blank=True, max_length=100, verbose_name='Причина расторжения')),
                ('datepolnop', models.DateField()),
                ('datenach', models.DateField(default=None)),
                ('dateokonch', models.DateField(default=None)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.progobuch')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договор',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viddoc', models.CharField(max_length=100, verbose_name='Вид документа')),
                ('datedoc', models.CharField(max_length=100, verbose_name='Дата выдачи документа')),
                ('nomerdoc', models.CharField(max_length=100, verbose_name='Номер')),
                ('seriadoc', models.CharField(max_length=100, verbose_name='Серия')),
                ('kemvidan', models.CharField(max_length=100, verbose_name='Кем выдан')),
                ('opisandoc', models.CharField(max_length=100, verbose_name='Описание документа')),
                ('fioUch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.ucheniki')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
