# Generated by Django 3.2.2 on 2021-06-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210616_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotrudniki',
            name='fam',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='otch',
            field=models.CharField(max_length=250, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='fam',
            field=models.CharField(max_length=250, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='otch',
            field=models.CharField(max_length=250, null=True, verbose_name='Отчество'),
        ),
    ]
