# Generated by Django 3.2.2 on 2021-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_rasp_teor_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasp_teor',
            name='tema',
            field=models.CharField(default='', max_length=250, verbose_name='Тема занятия'),
        ),
    ]
