# Generated by Django 3.2.2 on 2021-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210616_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucheniki',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Адрес проживания'),
        ),
    ]
