# Generated by Django 3.2.2 on 2021-06-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rasp_teor_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zurnal',
            name='nomer_zurnal',
        ),
    ]
