# Generated by Django 3.2.2 on 2021-06-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ucheniki_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotrudniki',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sotrudniki',
            name='tel',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='ucheniki',
            name='email',
            field=models.CharField(default='', max_length=150, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='ucheniki',
            name='tel',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
