# Generated by Django 3.2.2 on 2021-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_zurnal_nomer_zurnal'),
    ]

    operations = [
        migrations.AddField(
            model_name='zurnal',
            name='nomer_zurnal',
            field=models.CharField(default='', max_length=20, verbose_name='Номер Журнала'),
        ),
    ]
