# Generated by Django 3.2.2 on 2021-06-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_zurnal_nomer_zurnal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosZurnal',
        ),
    ]
