# Generated by Django 3.2.2 on 2021-06-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210617_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotrudniki',
            name='photo',
            field=models.CharField(default='', max_length=150, verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='ucheniki',
            name='photo',
            field=models.CharField(default='', max_length=150, verbose_name='Фотография'),
        ),
    ]
