# Generated by Django 3.2.2 on 2021-06-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_poszurnal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosZurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otmetka_pos', models.CharField(max_length=20, verbose_name='Посещаемость')),
                ('date_zan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.rasp_teor', verbose_name='Дата занятия')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика')),
                ('nomer_zurnal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.zurnal')),
            ],
            options={
                'verbose_name': 'Позиция журнала',
                'verbose_name_plural': 'Позиции журнала',
            },
        ),
    ]
