# Generated by Django 3.2.2 on 2021-06-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210617_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotrudniki',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='photo',
            field=models.CharField(max_length=150, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='sotrudniki',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='photo',
            field=models.CharField(max_length=150, verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
