# Generated by Django 3.2.2 on 2021-06-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_poszurnal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranport',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trvperiod',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='trvperiod',
            name='nazvavto',
        ),
        migrations.RemoveField(
            model_name='trvperiod',
            name='prog_obuch',
        ),
        migrations.RemoveField(
            model_name='trvperiod',
            name='tip_transm',
        ),
        migrations.AddField(
            model_name='tranport',
            name='fioSotr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AddField(
            model_name='tranport',
            name='gosnomer',
            field=models.CharField(default='', max_length=60, verbose_name='Гос.Номер'),
        ),
        migrations.AddField(
            model_name='tranport',
            name='nazvavto',
            field=models.CharField(default='', max_length=20, verbose_name='Макрка, модель'),
        ),
        migrations.AddField(
            model_name='tranport',
            name='tip_transm',
            field=models.CharField(default='', max_length=20, verbose_name='Тип трансмиссии'),
        ),
        migrations.AddField(
            model_name='trvperiod',
            name='fioSotr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AddField(
            model_name='trvperiod',
            name='fioUch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='documenti',
            name='fioUch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki'),
        ),
        migrations.AlterField(
            model_name='drivingcard',
            name='fioSotr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='drivingcard',
            name='fioUch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика'),
        ),
        migrations.AlterField(
            model_name='rasp_teor',
            name='fioSotr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='gosnomer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.tranport', verbose_name='Фио сотрудника'),
        ),
    ]
