# Generated by Django 3.2.2 on 2021-06-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210618_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranport',
            name='fioSotr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='tranport',
            name='gosnomer',
            field=models.CharField(max_length=60, verbose_name='Гос.Номер'),
        ),
        migrations.AlterField(
            model_name='tranport',
            name='nazvavto',
            field=models.CharField(max_length=20, verbose_name='Макрка, модель'),
        ),
        migrations.AlterField(
            model_name='tranport',
            name='tip_transm',
            field=models.CharField(max_length=20, verbose_name='Тип трансмиссии'),
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='fioSotr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='fioUch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио сотрудника'),
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='gosnomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tranport', verbose_name='Фио сотрудника'),
        ),
    ]
