# Generated by Django 3.2.2 on 2021-06-18 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210618_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Список групп', 'verbose_name_plural': 'Списки групп'},
        ),
        migrations.RemoveField(
            model_name='otchet',
            name='nomgrup',
        ),
        migrations.AddField(
            model_name='otchet',
            name='nazv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Номер группы'),
        ),
        migrations.CreateModel(
            name='Vedomost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_vedomost', models.IntegerField(verbose_name='Номер ведомости')),
                ('date_vedomost', models.DateField(verbose_name='Дата создания ведомости')),
                ('fioSotr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
        migrations.CreateModel(
            name='PosVedomost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20, verbose_name='Результат')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика')),
                ('nomer_vedomost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vedomost', verbose_name='Позиция ведомости')),
            ],
        ),
    ]
