# Generated by Django 3.2.2 on 2021-06-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210618_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='copy_doc',
            field=models.CharField(default='', max_length=100, verbose_name='Копия документа'),
        ),
    ]
