# Generated by Django 3.2.2 on 2021-06-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_documenti_copy_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasp_teor',
            name='nazv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Группа'),
        ),
        migrations.CreateModel(
            name='Rasp_praktiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_zan', models.DateTimeField(verbose_name='Дата занятия')),
                ('tema', models.CharField(default='', max_length=250, verbose_name='Тема занятия')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('fioSotr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='ФИО сотрудника')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='ФИО ученика')),
            ],
            options={
                'verbose_name': 'Расписание практических занятий',
                'verbose_name_plural': 'Расписание практических занятий',
            },
        ),
    ]
