# Generated by Django 3.2.2 on 2021-06-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210618_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fioSotr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sotrudniki', verbose_name='Фио сотрудника')),
                ('fioUch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='fioUch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ucheniki', verbose_name='Фио ученика'),
        ),
        migrations.AlterField(
            model_name='trvperiod',
            name='gosnomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tranport', verbose_name='Госномер'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время сообщения')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
            },
        ),
    ]
