# Generated by Django 3.2.2 on 2021-06-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210620_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucheniki',
            name='gruppa',
            field=models.CharField(default='', max_length=10, verbose_name='Группа'),
        ),
    ]
